### ISSUE TITLE
Меню: Не працює іконка дропдаун у використаних продуктах

### ISSUE THREAD

**Issue by Adilur** [ttp/trips#46]
1) Создать раскладку у которой продукт участвует 1 раз 
2) открыть раздел "Используемые продукты"

т.к дропдаун этого продукта не открывается то не видно дня в котором он используется и нельзя изменить норму.

![1](https://cloud.githubusercontent.com/assets/18736820/14914278/6aeb0822-0e11-11e6-9642-be11d64212f0.png)

**Comment by Adilur** [comment]
пардон, оказалось что надо жать на название продукта а не на дропдаун (неожиданно)

**Comment by ttp** [comment]
так, дійсно, підправлю

**Comment by ttp** [comment]
fixed
